namelist = """
BRENDON CHAN YI MING
CHENG HENG YOKE ELLA
CHERYL CHEAM SHUQING
FU JINGHANG
GABRIEL KHOO KEN JIN
HE YUXIN DAVID
HEBE TANG QIAO EN
HUANG JU
KAYDEN LAU CHUNG RUI
LAU HEI YUET
LEE JUN HUI, TORRES
LEE KE YI KENDRICK
LEE XIN LE
LEE YUIN ER
LEONG SHU HAO
LIU SHIJIA
MENG ZHANFEI JEFFREY
MING PEACH (LIU MINGMING)
NATALIE WONG YU LER
NEO CZE EN
NG QI WEI
PAN BOLIN
TAN E-JUN (CHEN YIJUN)
UALI TOKTAR
WANG JINGBO
YANG HABIN
"""

names = namelist.split('\n')
for name in names:
    print(name.title())